server {
    listen 80;
    server_name news.rubymaelstrom.com;

    # --- Main news feed page
    location /news {
        content_by_lua_file /etc/nginx/lua/handlers/index.lua;
    }

    # --- Article detail page
    location /news/article {
        content_by_lua_file /etc/nginx/lua/handlers/article.lua;
    }

    # --- Country edition selector
    location /news/choose_edition {
        content_by_lua_file /etc/nginx/lua/handlers/choose_edition.lua;
    }
}
